services:
  redis:
    image: redis:7
    container_name: rate-limiting-redis
    ports:
      - '6379:6379'
    command: ['redis-server', '--appendonly', 'yes']
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  redis-data: